apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: chatbot-webapp:latest
          ports:
            - containerPort: 8050
          env:
            - name: MODEL_RUNNER_URL
              valueFrom:
                configMapKeyRef:
                  name: chatbot-config
                  key: llm_url
