services:
  llm:
    image: ollama/ollama:0.12.4
    container_name: llm_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/bash"]
    command: ["-c", "ollama serve & sleep 10 && ollama pull gemma2:2b && wait"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/tags || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: webapp
    environment:
      MODEL_RUNNER_URL: "http://llm:11434"
    ports:
      - "8050:8050"
    depends_on:
      - llm

volumes:
  ollama_data:



